# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test -c Release --no-build

    - name: Publish 
      run: dotnet publish SpeechToTranslated/SpeechToTranslated.csproj --runtime win-x64 --self-contained -c Release --output ./Publish
    - name: Publish 
      run: dotnet publish TranslateWordsConsole/TranslateWordsConsole.csproj --runtime win-x64 --self-contained -c Release --output ./Publish
    - name: Publish 
      run: dotnet publish TranslateWordsGui/TranslateWordsGui.csproj --runtime win-x64 --self-contained -c Release --output ./Publish

    - name: Publish Linux
      run: dotnet publish SpeechToTranslated/SpeechToTranslated.csproj --runtime linux-x64 --self-contained -c ReleaseLinux --output ./PublishLinux
    - name: Publish Linux
      run: dotnet publish TranslateWordsConsole/TranslateWordsConsole.csproj --runtime linux-x64 --self-contained -c ReleaseLinux --output ./PublishLinux
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build result
        path: ./Publish/
    - name: Upload Linux build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Linux build result
        path: ./PublishLinux/
